language: php
php:
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - php ./developer/lint-php.php
  - ./developer/phpcompat.sh

notifications:
  email:
    recipients:
      - boonebgorges+openlab@gmail.com
    on_success: change
    on_failure: change
