language: php
php:
  - 7.2
  - 7.3

before_script:
  - composer install

script:
  - ./developer/phpcompat.sh

notifications:
  email:
    recipients:
      - boonebgorges+openlab@gmail.com
    on_success: change
    on_failure: change
