language: php
php:
  - 7.2
  - nightly

script: php developer/lint-php.php

notifications:
  email:
    recipients:
      - boonebgorges+openlab@gmail.com
    on_success: change
    on_failure: always
